CREATE DATABASE music CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE artists(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, name VARCHAR(50) NOT NULL, instrument VARCHAR(50), artistImage mediumblob NOT NULL);

CREATE TABLE albums(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, name VARCHAR(50) NOT NULL, releaseDate int(10), albumCover mediumblob NOT NULL);

CREATE TABLE songs(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, artistId INT NOT NULL, albumId INT NOT NULL, song mediumblob NOT NULL, title VARCHAR(50) NOT NULL, genre VARCHAR(50) NOT NULL, `language` VARCHAR(50) NOT NULL);

ALTER TABLE songs
FOREIGN KEY (artistId) REFERENCES artists(id)
ON DELETE CASCADE,
FOREIGN KEY (albumId) REFERENCES albums(id)
ON DELETE CASCADE;